/**
 * Constants for seed user IDs and relationship data.
 * These match the deterministic IDs generated by `packages/db/src/seed.ts`.
 *
 * Run `bun run db:seed` to populate the database with this data.
 */

function seedId(name: string): string {
	return `seed_${name}`.padEnd(25, "0");
}

export const SEED_USERS = {
	agucova: {
		id: seedId("agucova"),
		name: "Agustín Covarrubias",
		username: "agucova",
		email: "gloss@agucova.dev",
	},
	alice: {
		id: seedId("alice"),
		name: "Alice Chen",
		username: "alicechen",
		email: "alice@example.com",
	},
	bob: {
		id: seedId("bob"),
		name: "Bob Martinez",
		username: "bobm",
		email: "bob@example.com",
	},
	carol: {
		id: seedId("carol"),
		name: "Carol Davis",
		username: "carol",
		email: "carol@example.com",
	},
	dan: {
		id: seedId("dan"),
		name: "Dan Wilson",
		username: "danw",
		email: "dan@example.com",
	},
	eve: {
		id: seedId("eve"),
		name: "Eve Johnson",
		username: "evej",
		email: "eve@example.com",
	},
} as const;

// Accepted friendships (bidirectional):
// agucova <-> alice, bob, carol, eve
// alice <-> bob, carol
// bob <-> eve
// carol <-> eve
// Pending: dan -> agucova
