import { env } from "@gloss/env/server";
import { drizzle } from "drizzle-orm/node-postgres";
import {
	account,
	accountRelations,
	apiKey,
	apiKeyRelations,
	apiKeyScopeEnum,
	bookmark,
	bookmarkRelations,
	bookmarkTag,
	bookmarkTagRelations,
	comment,
	commentMention,
	commentMentionRelations,
	commentRelations,
	curiusCredentials,
	curiusCredentialsRelations,
	curiusUserMapping,
	curiusUserMappingRelations,
	friendship,
	friendshipRelations,
	friendshipStatusEnum,
	highlight,
	highlightRelations,
	searchEntityTypeEnum,
	searchIndex,
	searchIndexRelations,
	session,
	sessionRelations,
	tag,
	tagRelations,
	user,
	userRelations,
	verification,
	visibilityEnum,
} from "./schema";

const schema = {
	user,
	session,
	account,
	verification,
	userRelations,
	sessionRelations,
	accountRelations,
	apiKey,
	apiKeyRelations,
	apiKeyScopeEnum,
	bookmark,
	bookmarkRelations,
	highlight,
	highlightRelations,
	visibilityEnum,
	curiusCredentials,
	curiusCredentialsRelations,
	curiusUserMapping,
	curiusUserMappingRelations,
	friendship,
	friendshipRelations,
	friendshipStatusEnum,
	comment,
	commentRelations,
	commentMention,
	commentMentionRelations,
	tag,
	tagRelations,
	bookmarkTag,
	bookmarkTagRelations,
	searchIndex,
	searchIndexRelations,
	searchEntityTypeEnum,
};

export const db = drizzle(env.DATABASE_URL, { schema });
