/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReadLaterRouteImport } from './routes/read-later'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InstallRouteImport } from './routes/install'
import { Route as IndexRouteImport } from './routes/index'
import { Route as USetupRouteImport } from './routes/u/setup'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as CliAuthorizeRouteImport } from './routes/cli/authorize'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadLaterRoute = ReadLaterRouteImport.update({
  id: '/read-later',
  path: '/read-later',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const USetupRoute = USetupRouteImport.update({
  id: '/u/setup',
  path: '/u/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthorizeRoute = CliAuthorizeRouteImport.update({
  id: '/cli/authorize',
  path: '/cli/authorize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/read-later': typeof ReadLaterRoute
  '/settings': typeof SettingsRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/u/$username': typeof UUsernameRoute
  '/u/setup': typeof USetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/read-later': typeof ReadLaterRoute
  '/settings': typeof SettingsRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/u/$username': typeof UUsernameRoute
  '/u/setup': typeof USetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/read-later': typeof ReadLaterRoute
  '/settings': typeof SettingsRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/u/$username': typeof UUsernameRoute
  '/u/setup': typeof USetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/install'
    | '/library'
    | '/login'
    | '/profile'
    | '/read-later'
    | '/settings'
    | '/cli/authorize'
    | '/u/$username'
    | '/u/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/install'
    | '/library'
    | '/login'
    | '/profile'
    | '/read-later'
    | '/settings'
    | '/cli/authorize'
    | '/u/$username'
    | '/u/setup'
  id:
    | '__root__'
    | '/'
    | '/install'
    | '/library'
    | '/login'
    | '/profile'
    | '/read-later'
    | '/settings'
    | '/cli/authorize'
    | '/u/$username'
    | '/u/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstallRoute: typeof InstallRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReadLaterRoute: typeof ReadLaterRoute
  SettingsRoute: typeof SettingsRoute
  CliAuthorizeRoute: typeof CliAuthorizeRoute
  UUsernameRoute: typeof UUsernameRoute
  USetupRoute: typeof USetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read-later': {
      id: '/read-later'
      path: '/read-later'
      fullPath: '/read-later'
      preLoaderRoute: typeof ReadLaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/setup': {
      id: '/u/setup'
      path: '/u/setup'
      fullPath: '/u/setup'
      preLoaderRoute: typeof USetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/authorize': {
      id: '/cli/authorize'
      path: '/cli/authorize'
      fullPath: '/cli/authorize'
      preLoaderRoute: typeof CliAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstallRoute: InstallRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReadLaterRoute: ReadLaterRoute,
  SettingsRoute: SettingsRoute,
  CliAuthorizeRoute: CliAuthorizeRoute,
  UUsernameRoute: UUsernameRoute,
  USetupRoute: USetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
